
--Q1 total revenue generated by male vs. female customer
SELECT gender, SUM(total_price) AS revenue
from customer_behavior
where gender is not null
group by gender;

--Q2 which customers used a discount 
--Q3 product with the highest review rating 
select product_type, AVG(rating) AS "Average Product RAting"
from customer_behavior
group by product_type
order by avg(rating) desc
limit 5;

--Q4. purchase Amount between standard and express shipping comparison
select shipping_type,
ROUND(AVG(total_price)::numeric,2)
from customer_behavior
where shipping_type in ('Standard','Overnight','Express')
group by shipping_type;

--Q5 Do subscribed customers spend more?Compare average spend and total revenue between subscribers and non-subscribers
select loyalty_member, 
COUNT(customer_id) AS total_customers,
ROUND(AVG(total_price)::numeric,2) AS avg_spend,
ROUND(SUM(total_price)::numeric,2) AS total_revenue
from customer_behavior
group by loyalty_member
order by total_revenue, avg_spend desc;

--Q6, which products have the highest % of purchases with Add-on total?
select product_type,
ROUND((SUM(CASE WHEN add_on_total > 0 THEN 1 ELSE 0 END)::numeric /COUNT(*)) * 100,2) AS add_on_rate
FROM customer_behavior 
group by product_type
order by add_on_rate desc
limit 5;

--Q7, segment customers into new, returning and loyal based on their total number of previous purchases
--Q8, top 3 most purchased product 
with item_counts as (
    select add_ons_purchased, 
    product_type,
    COUNT(customer_id) as total_orders,
    ROW_NUMBER() OVER(PARTITION BY product_type ORDER BY COUNT(customer_id) DESC) AS item_rank
    from customer_behavior 
    group by add_ons_purchased, product_type
)

select item_rank, product_type, total_orders
from item_counts
where item_rank <= 3;

--Q9, customers who are repeat buyers 
select loyalty_member, 
COUNT(customer_id) AS repeat_buyers 
FROM customer_behavior
where quantity > 5
group by loyalty_member;

--Q10, revenue by age group 
select age_group,
SUM(total_price) AS total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;